version: '3.7'
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uniqlo
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306" # Map host port 3307 to container port 3306
    volumes:
      - ./mysql-db:/data/mysql
  # mysql -h 127.0.0.1 -P 3307 -u myuser -pmypassword

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  discovery-server:
    image: leexizhe17/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "9999:9999"
    depends_on:
      - zipkin

#  api-gateway:
#    image: leexizhe17/api-gateway:latest
#    container_name: api-gateway
#    pull_policy: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - zipkin
#      - discovery-server
#
#  product-service:
#    container_name: product-service
#    image: leexizhe17/product-service:latest
#    pull_policy: always
#    ports:
#      - "1000:1000"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/uniqlo?useSSL=false
#      - SPRING_DATASOURCE_USERNAME=myuser
#      - SPRING_DATASOURCE_PASSWORD=mypassword
#    depends_on:
#      - mysql
#      - discovery-server
#      - api-gateway