server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates: Path=/api/product
        - id: order-service
          uri: lb://order-service
          predicates: Path=/api/order
        - id: discovery-server
          uri: http://localhost:9999
          predicates: Path=/eureka
          filters: SetPath=/
        - id: discovery-server-static
          uri: http://localhost:9999
          predicates: Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO



