server:
  port: 2000

spring:
  application:
    name: order-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/uniqlo?useSSL=false
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
    instances:
      inventory: # Replace with your desired Circuit Breaker name
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
resilience4j.timelimiter:
    instances:
      inventory:
        timeout-duration: 3000


logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
