server:
  port: 3000

spring:
  application:
    name: inventory-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/uniqlo?useSSL=false
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG


