server:
  port: 1020

spring:
  application:
    name: inventory-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/uniqlo?useSSL=false
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

logging:
  level:
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.sleuth: DEBUG # Set the logging level for Sleuth
    org.springframework.cloud.sleuth.instrument.web: DEBUG # Set the logging level for Sleuth's web instrumentation